name: Flatpak
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
env:
  GO_VERSION: '1.20'
jobs:
  flatpak:
    name: "Flatpak"
    runs-on: ubuntu-latest
    container:
      image: bilelmoussaoui/flatpak-github-actions:gnome-45
      options: --privileged
    strategy:
      matrix:
        arch: [x86_64, aarch64]
      fail-fast: false
    steps:
    - uses: actions/checkout@v4
    - name: Install deps
      if: ${{ matrix.arch != 'x86_64' }}
      run: |
        dnf -y install docker
    - name: Set up QEMU
      if: ${{ matrix.arch != 'x86_64' }}
      id: qemu
      uses: docker/setup-qemu-action@v2
      with:
        platforms: arm64
    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: ${{ env.GO_VERSION }}
    - name: Install libfido2-dev
      run: sudo dnf install -y libfido2-devel
    - name: Build
      run: go build -o goldwarden -v .
    - uses: flatpak/flatpak-github-actions/flatpak-builder@v6
      with:
        bundle: goldwarden.flatpak
        manifest-path: com.quexten.Goldwarden.yml
        cache-key: flatpak-builder-${{ github.sha }}
        arch: ${{ matrix.arch }}