on:
  release:
    types: [created]

permissions:
    contents: write
    packages: write

jobs:
  build_linux_x86_64:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.20'

    - name: Install libfido2-dev
      run: sudo apt-get install -y libfido2-dev

    - name: Install gio dependencies
      run: sudo apt-get install -y gcc pkg-config libwayland-dev libx11-dev libx11-xcb-dev libxkbcommon-x11-dev libgles2-mesa-dev libegl1-mesa-dev libffi-dev libxcursor-dev libvulkan-dev
  
    - name: Build with Autofill
      run: go build -tags autofill -o goldwarden -v .

    - uses: AButler/upload-release-assets@v2.0
      with:
        files: './goldwarden'
        repo-token: ${{ secrets.GITHUB_TOKEN }}

    - name: Validate ArchLinux PKGBUILD
      uses: hapakaien/archlinux-package-action@v2
      with:
        flags: ''
        namcap: true
        updpkgsums: true

    - name: Build ArchLinux package
      uses: mijailr/arch-makepkg-action@v1

      
    - uses: AButler/upload-release-assets@v2.0
      with:
        files: './*.pkg.tar.zst'
        repo-token: ${{ secrets.GITHUB_TOKEN }}


  
