on:
  release:
    types: [created]

permissions:
    contents: write
    packages: write

jobs:
  build_linux_x86_64:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.20'

    - name: Install libfido2-dev
      run: sudo apt-get install -y libfido2-dev

    - name: Install gio dependencies
      run: sudo apt-get install -y gcc pkg-config libwayland-dev libx11-dev libx11-xcb-dev libxkbcommon-x11-dev libgles2-mesa-dev libegl1-mesa-dev libffi-dev libxcursor-dev libvulkan-dev
  
    - name: Build with All features
      run: go build -o goldwarden -v .
    - name: Build minimal featureset
      run: go build -tags nofido2 -tags noautofill -o goldwarden-minimal -v .
    - uses: AButler/upload-release-assets@v2.0
      with:
        files: './goldwarden;./goldwarden-minimal'
        repo-token: ${{ secrets.GITHUB_TOKEN }}
    - name: Validate ArchLinux PKGBUILD
      uses: hapakaien/archlinux-package-action@v2
      with:
        flags: ''
        namcap: true
        updpkgsums: true
    - name: Publish AUR package
      uses: KSXGitHub/github-actions-deploy-aur@v2.7.0
      with:
        pkgname: goldwarden
        updpkgsums: true
        pkgbuild: ./PKGBUILD
        commit_username: ${{ secrets.AUR_USERNAME }}
        commit_email: ${{ secrets.AUR_EMAIL }}
        ssh_private_key: ${{ secrets.AUR_SSH_PRIVATE_KEY }}
        commit_message: Update AUR package from GitHub Actions automation
        ssh_keyscan_types: ed25519

  build_macos_x86_64:
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.20'
      - name: Build 
        run: go build -tags "nofido2 noautofill" -v .
      - uses: actions/upload-artifact@v3
        with:
          name: goldwarden-macos_x86_64
          path: ./goldwarden

  build_windows_x86_64:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.20'
      - name: Build 
        run: go build -tags "nofido2 noautofill" -v .
      - uses: actions/upload-artifact@v3
        with:
          name: goldwarden-windows_x86_64.exe
          path: ./goldwarden.exe